services:
  - type: web
    name: hei-journal-ojs
    runtime: docker
    plan: free
    healthCheckPath: /index.php/heijournal
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_USER
        value: ojs
      - key: DB_PASSWORD
        value: ojs
      - key: DB_NAME
        value: ojs_local
      - key: BASE_URL
        sync: false
      - key: FILES_DIR
        value: /var/www/files
